import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
import { BrowserMultiFormatReader } from 'https://esm.sh/@zxing/browser@0.1.5';
import { BarcodeFormat, DecodeHintType } from 'https://esm.sh/@zxing/library@0.21.3';
import Quagga from 'https://esm.sh/@ericblade/quagga2@1.12.1';

const SUPABASE_URL='https://dkqovohxkxlcccvagpij.supabase.co';
const SUPABASE_KEY='sb_publishable_iz06RtaObND0dWOpuX2vKg_wZVbrZCv';
const sb=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const app=document.getElementById('app');
let session=null, tab='scan', scanControls=null, scanning=false, lastDetected='', lastDetectedAt=0, selectedProduct=null, selectedType='VENTA';
const fmt=[BarcodeFormat.EAN_13,BarcodeFormat.EAN_8,BarcodeFormat.UPC_A,BarcodeFormat.UPC_E,BarcodeFormat.CODE_128,BarcodeFormat.CODE_39,BarcodeFormat.CODE_93,BarcodeFormat.ITF,BarcodeFormat.CODABAR,BarcodeFormat.RSS_14,BarcodeFormat.RSS_EXPANDED].filter(Boolean);
const hints=new Map([[DecodeHintType.POSSIBLE_FORMATS,fmt],[DecodeHintType.TRY_HARDER,true],[DecodeHintType.ALSO_INVERTED,true]]);

function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(v){return new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(v||0))}
function nowId(){return crypto.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`}
function emailFromKey(k){return `${String(k).trim().toLowerCase()}@bodega.local`}
function passFrom(k,p){return `bodega-${String(k).trim()}-${String(p).trim()}`}
async function getSession(){const {data:{user}}=await sb.auth.getUser(); if(!user)return null; const [{data:p},{data:r}]=await Promise.all([sb.from('perfiles').select('clave,nombre,activo').eq('id',user.id).maybeSingle(),sb.from('user_roles').select('role').eq('user_id',user.id)]); const roles=(r||[]).map(x=>x.role); return {id:user.id,clave:p?.clave||'',nombre:p?.nombre||'Usuario',activo:p?.activo!==false,roles,admin:roles.includes('ADMIN'),staff:roles.includes('ADMIN')||roles.includes('BODEGA')};}
async function boot(){session=await getSession(); render(); if('serviceWorker'in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});}
function render(){if(!session)return renderLogin(); return renderShell();}
function renderLogin(){app.innerHTML=`<main class="login"><div style="width:min(100%,380px)"><div style="text-align:center;margin-bottom:24px"><img src="icon.svg" width="76" height="76" style="border-radius:20px"><h1>Control de Bodega</h1><p class="sub">Inventario de tienda en tiempo real</p></div><form id="login" class="card"><label>Clave de empleado</label><input id="clave" inputmode="numeric" autocomplete="username" placeholder="Ej. 99"><label>PIN</label><input id="pin" type="password" inputmode="numeric" autocomplete="current-password" placeholder="••••"><div id="loginerr"></div><button class="btn" style="margin-top:16px">Entrar</button></form></div></main>`; document.getElementById('login').onsubmit=async e=>{e.preventDefault(); const k=clave.value.trim(),p=pin.value.trim(); loginerr.innerHTML=''; if(!k||!p){loginerr.innerHTML='<div class="error">Escribe clave y PIN.</div>';return} const b=e.submitter;b.disabled=true;b.textContent='Entrando…'; const {error}=await sb.auth.signInWithPassword({email:emailFromKey(k),password:passFrom(k,p)}); b.disabled=false;b.textContent='Entrar'; if(error){loginerr.innerHTML='<div class="error">Clave o PIN incorrectos.</div>';return} session=await getSession(); if(!session){loginerr.innerHTML='<div class="error">El usuario existe pero no tiene perfil activo.</div>';return} render();};}
function nav(){return `<nav class="tabs"><button data-tab="scan" class="${tab==='scan'?'active':''}">Escanear</button><button data-tab="inventory" class="${tab==='inventory'?'active':''}">Inventario</button>${session.staff?`<button data-tab="admin" class="${tab==='admin'?'active':''}">Admin</button>`:''}</nav>`}
function renderShell(){let body=tab==='scan'?scanView():tab==='inventory'?inventoryView():adminView();app.innerHTML=`<div class="wrap"><div class="top"><div><h2 style="margin:0">Control de Bodega</h2><div class="small">${esc(session.nombre)} · clave ${esc(session.clave)} · ${esc(session.roles[0]||'')}</div></div><button id="logout" class="btn-light">Salir</button></div>${body}</div>${nav()}`; document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;stopScanner();render()}); document.getElementById('logout').onclick=async()=>{stopScanner();await sb.auth.signOut();session=null;render()}; wireTab();}
function scanView(){return `<section><div class="grid3">${['VENTA','DEVOLUCION','ENTRADA'].map(t=>`<button class="type ${selectedType===t?'active':''}" data-type="${t}">${t==='VENTA'?'−':'+'}<br>${t==='DEVOLUCION'?'Devolución':t[0]+t.slice(1).toLowerCase()}</button>`).join('')}</div><button id="openCam" class="btn-accent" style="width:100%;margin:12px 0">📷 Abrir cámara</button><div class="card"><form id="lookup"><label>SKU / código de barras</label><div class="row"><input id="skuManual" placeholder="Escanea o escribe el código"><button class="btn-light" style="flex:0 0 auto">Buscar</button></div></form><div id="productBox" style="margin-top:12px">${selectedProduct?productForm(selectedProduct):'<p class="sub">Escanea un código para cargar el producto.</p>'}</div></div><div id="msg" style="margin-top:12px"></div></section>`}
function productForm(p){let st=p.stock<=0?'<span class="badge bad">Agotado</span>':p.stock<=p.stock_minimo?'<span class="badge warn">Stock bajo</span>':'<span class="badge good">Disponible</span>';return `<div><div class="small">${esc(p.sku)}</div><h3>${esc(p.descripcion)}</h3><p class="sub">${esc([p.marca,p.talla,p.color].filter(Boolean).join(' · '))} · ${money(p.precio)}</p><div class="row"><div><div class="small">Stock</div><div class="stock">${p.stock}</div></div><div style="text-align:right">${st}</div></div><label>Cantidad</label><input id="qty" type="number" min="1" value="1" inputmode="numeric"><label>Área</label><select id="area"><option>piso</option><option>caja</option><option>bodega</option></select><label>Nota (opcional)</label><input id="note" placeholder="Ej. cambio de talla"><button id="saveMove" class="btn" style="margin-top:14px">Registrar movimiento</button></div>`}
function inventoryView(){return `<section><div class="card"><label>Buscar inventario</label><input id="invSearch" placeholder="SKU, descripción, marca, talla o color"><div id="invList" style="margin-top:10px"><p class="sub">Cargando…</p></div></div></section>`}
function adminView(){if(!session.staff)return '<div class="error">Sin permiso.</div>'; return `<section><div id="kpis" class="kpis"><div class="kpi"><span class="small">Ventas hoy</span><br><strong>…</strong></div><div class="kpi"><span class="small">Devoluciones</span><br><strong>…</strong></div><div class="kpi"><span class="small">SKUs</span><br><strong>…</strong></div><div class="kpi"><span class="small">Stock bajo</span><br><strong>…</strong></div></div><div class="card" style="margin-top:12px"><h3>Movimientos recientes</h3><div id="moves">Cargando…</div></div></section>`}
function wireTab(){document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{selectedType=b.dataset.type;render()}); if(tab==='scan'){openCam.onclick=startScanner;lookup.onsubmit=e=>{e.preventDefault();lookupSku(skuManual.value)};document.getElementById('saveMove')?.addEventListener('click',saveMovement)} if(tab==='inventory')loadInventory(); if(tab==='admin')loadAdmin();}
async function lookupSku(code){code=String(code||'').trim(); if(!code)return; const {data,error}=await sb.from('productos').select('*').eq('sku',code).maybeSingle(); if(error){stopScanner();selectedProduct=null;render();setTimeout(()=>showMsg('No se pudo consultar el producto.','error'));return} if(!data){stopScanner();selectedProduct=null;render();setTimeout(()=>showMsg(`SKU ${esc(code)} no encontrado.`,'error'));return} selectedProduct=data;stopScanner();render();setTimeout(()=>showMsg(`Código leído: ${esc(code)}`,'success'));}
function showMsg(t,cls='success'){const x=document.getElementById('msg');if(x)x.innerHTML=`<div class="${cls}">${t}</div>`}
async function saveMovement(){if(!selectedProduct)return;const q=Math.max(1,Number(qty.value)||1);if(selectedType==='VENTA'&&q>selectedProduct.stock){showMsg(`Stock insuficiente. Hay ${selectedProduct.stock}.`,'error');return}const btn=saveMove;btn.disabled=true;btn.textContent='Registrando…';const {data,error}=await sb.rpc('registrar_movimiento',{p_id:nowId(),p_sku:selectedProduct.sku,p_tipo:selectedType,p_cantidad:q,p_area:area.value,p_nota:note.value.trim()||null});btn.disabled=false;btn.textContent='Registrar movimiento';if(error){showMsg(esc(error.message),'error');return}const row=Array.isArray(data)?data[0]:data;selectedProduct={...selectedProduct,stock:row?.stock_resultante??selectedProduct.stock};showMsg(`Movimiento registrado. Stock actual: ${selectedProduct.stock}`);render();}
function acceptDetected(value){value=String(value||'').trim();if(!value)return;const now=Date.now();if(value===lastDetected&&now-lastDetectedAt<2200)return;lastDetected=value;lastDetectedAt=now;lookupSku(value);}
async function startScanner(){if(scanning)return;scanning=true; app.insertAdjacentHTML('beforeend',`<div class="scanner" id="scanner"><div class="scanner-head"><b>Apunta al código de barras</b><button id="closeScan" class="btn-light">✕</button></div><div id="scannerViewport" style="position:relative;flex:1;overflow:hidden"><video id="video" muted playsinline></video><div class="guide"></div></div><div class="scanner-note">Lector reforzado · EAN, UPC, CODE-128, CODE-39, CODE-93, ITF / Interleaved 2 of 5 y CODABAR</div></div>`);closeScan.onclick=stopScanner;
try{
  const qTarget=document.getElementById('scannerViewport');
  const qReaders=['code_128_reader','ean_reader','ean_8_reader','upc_reader','upc_e_reader','code_39_reader','code_39_vin_reader','code_93_reader','codabar_reader','i2of5_reader','2of5_reader'];
  const qConfig={inputStream:{type:'LiveStream',target:qTarget,constraints:{facingMode:'environment',width:{min:1280,ideal:1920},height:{min:720,ideal:1080}},area:{top:'8%',right:'3%',left:'3%',bottom:'8%'}},locator:{patchSize:'medium',halfSample:false},numOfWorkers:Math.min(4,navigator.hardwareConcurrency||2),frequency:18,decoder:{readers:qReaders,multiple:false},locate:true};
  try{
    await new Promise((resolve,reject)=>Quagga.init(qConfig,err=>err?reject(err):resolve()));
    if(!scanning)return;
    Quagga.onDetected(data=>{const value=data?.codeResult?.code;const errors=(data?.codeResult?.decodedCodes||[]).filter(x=>typeof x.error==='number').map(x=>x.error);const avg=errors.length?errors.reduce((a,b)=>a+b,0)/errors.length:0;if(value && avg<0.5)acceptDetected(value)});
    Quagga.start(); scanControls={stop:()=>{try{Quagga.stop()}catch{}}};
    const track=Quagga.CameraAccess?.getActiveTrack?.();
    if(track){const caps=track.getCapabilities?.()||{};const adv={};if(Array.isArray(caps.focusMode)&&caps.focusMode.includes('continuous'))adv.focusMode='continuous';if(caps.zoom){const z=Math.min(caps.zoom.max||1.8,Math.max(caps.zoom.min||1,1.5));adv.zoom=z}if(Object.keys(adv).length)track.applyConstraints({advanced:[adv]}).catch(()=>{})}
  }catch(qErr){
    const reader=new BrowserMultiFormatReader(hints,{delayBetweenScanAttempts:60,delayBetweenScanSuccess:500});
    scanControls=await reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}}},document.getElementById('video'),result=>{if(result)acceptDetected(result.getText())});
    const video=document.getElementById('video');const track=video?.srcObject?.getVideoTracks?.()[0];if(track){const caps=track.getCapabilities?.()||{};const adv={};if(caps.focusMode?.includes?.('continuous'))adv.focusMode='continuous';if(caps.zoom){const z=Math.min(Math.max(1.5,caps.zoom.min||1),caps.zoom.max||1.5);adv.zoom=z}if(Object.keys(adv).length)track.applyConstraints({advanced:[adv]}).catch(()=>{})}
  }
}catch(e){scanning=false;document.getElementById('scanner')?.remove();showMsg('No se pudo abrir la cámara. Revisa el permiso de Safari e inténtalo otra vez.','error')}}
function stopScanner(){try{scanControls?.stop?.()}catch{}try{Quagga.offDetected?.()}catch{}scanControls=null;scanning=false;document.getElementById('scanner')?.remove();}
async function loadInventory(){const el=invList;const {data,error}=await sb.from('productos').select('sku,descripcion,marca,talla,color,precio,stock,stock_minimo').order('descripcion');if(error){el.innerHTML='<div class="error">No se pudo cargar.</div>';return}const draw=q=>{q=(q||'').toLowerCase();const rows=data.filter(p=>!q||[p.sku,p.descripcion,p.marca,p.talla,p.color].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)));el.innerHTML=rows.map(p=>`<div class="product"><div><b>${esc(p.descripcion)}</b><div class="small">${esc(p.sku)} · ${esc([p.marca,p.talla,p.color].filter(Boolean).join(' · '))}</div></div><div style="text-align:right"><div class="stock">${p.stock}</div><div class="small">mín ${p.stock_minimo}</div></div></div>`).join('')||'<p class="sub">Sin resultados.</p>'};draw('');invSearch.oninput=()=>draw(invSearch.value)}
async function loadAdmin(){const start=new Date();start.setHours(0,0,0,0);const [m,p]=await Promise.all([sb.from('movimientos').select('*').gte('created_at',start.toISOString()).order('created_at',{ascending:false}).limit(50),sb.from('productos').select('sku,stock,stock_minimo')]);if(m.error||p.error)return;const ventas=m.data.filter(x=>x.tipo==='VENTA').reduce((s,x)=>s+x.cantidad,0),dev=m.data.filter(x=>x.tipo==='DEVOLUCION').reduce((s,x)=>s+x.cantidad,0),low=p.data.filter(x=>x.stock>0&&x.stock<=x.stock_minimo).length;kpis.innerHTML=`<div class="kpi"><span class="small">Ventas hoy</span><br><strong>${ventas}</strong></div><div class="kpi"><span class="small">Devoluciones</span><br><strong>${dev}</strong></div><div class="kpi"><span class="small">SKUs</span><br><strong>${p.data.length}</strong></div><div class="kpi"><span class="small">Stock bajo</span><br><strong>${low}</strong></div>`;moves.innerHTML=m.data.map(x=>`<div class="product"><div><b>${esc(x.tipo)} · ${x.cantidad}</b><div class="small">${esc(x.sku)} · ${esc(x.user_nombre)} · ${new Date(x.created_at).toLocaleString('es-MX')}</div></div><b>${x.stock_resultante}</b></div>`).join('')||'<p class="sub">Sin movimientos.</p>'}
boot();