const X=B,$=id=>document.getElementById(id),app=$('app');
X.$=$;X.esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
X.money=v=>Number.isFinite(Number(v))?new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(v)):String(v??'');
X.uuid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
async function hash(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function empMatch(c,p){for(const e of X.EMPLOYEES)if(e.c===c&&await hash(`${e.s}:${p}`)===e.h)return e;return null}
async function adminInfo(){const {data:{user}}=await X.sb.auth.getUser();if(!user)return null;const [a,b]=await Promise.all([X.sb.from('perfiles').select('clave,nombre,activo,puesto').eq('id',user.id).maybeSingle(),X.sb.from('user_roles').select('role').eq('user_id',user.id)]);if(!a.data||a.data.activo===false)return null;const roles=(b.data||[]).map(x=>x.role);return{mode:'admin',id:user.id,clave:a.data.clave,nombre:a.data.nombre,puesto:a.data.puesto||'',staff:roles.includes('ADMIN')||roles.includes('BODEGA')}}
X.boot=async()=>{let saved=null;try{saved=JSON.parse(localStorage.getItem('bodegaEmpleado')||'null')}catch{}const {data:{user}}=await X.sb.auth.getUser();if(user&&saved)X.S={mode:'employee',id:user.id,...saved,staff:false};else if(user)X.S=await adminInfo();X.render();navigator.serviceWorker?.register('./sw.js').catch(()=>{})};
X.render=()=>{if(!X.S)return loginView();shell()};
function loginView(){app.innerHTML=`<main class="login"><div style="width:min(100%,390px)"><div style="text-align:center;margin-bottom:24px"><img src="icon.svg" width="78" height="78" style="border-radius:20px"><h1>Control de Bodega</h1><p class="sub">Inventario, UPC y ubicaciones en tiempo real</p></div><form id="login" class="card"><label>Clave</label><input id="clave" inputmode="numeric" placeholder="10 o 99"><label>PIN</label><input id="pin" type="password" inputmode="numeric" placeholder="••••••••"><div id="loginerr"></div><button class="btn" style="margin-top:16px">Entrar</button></form></div></main>`;$('login').onsubmit=doLogin}
async function doLogin(e){e.preventDefault();const c=$('clave').value.trim(),p=$('pin').value.trim(),b=e.submitter;$('loginerr').innerHTML='';b.disabled=true;b.textContent='Validando…';try{if(c==='99'){localStorage.removeItem('bodegaEmpleado');const {error}=await X.sb.auth.signInWithPassword({email:'99@bodega.local',password:`bodega-99-${p}`});if(error)throw Error('Clave o PIN incorrectos.');X.S=await adminInfo();if(!X.S)throw Error('Perfil administrador no disponible.')}else{const x=await empMatch(c,p);if(!x)throw Error('Clave o PIN incorrectos.');const {error}=await X.sb.auth.signInWithPassword({email:'10@bodega.local',password:'bodega-10-1010'});if(error)throw Error('No se pudo abrir la sesión de tienda.');const {data:{user}}=await X.sb.auth.getUser();X.S={mode:'employee',id:user?.id||'',clave:x.c,nombre:x.n,puesto:x.p,staff:false};localStorage.setItem('bodegaEmpleado',JSON.stringify({clave:x.c,nombre:x.n,puesto:x.p}))}X.render()}catch(x){$('loginerr').innerHTML=`<div class="error">${X.esc(x.message)}</div>`}finally{b.disabled=false;b.textContent='Entrar'}}
function nav(){return`<nav class="tabs"><button data-tab="scan" class="${X.tab==='scan'?'active':''}">Escanear</button><button data-tab="inventory" class="${X.tab==='inventory'?'active':''}">Inventario</button>${X.S.staff?`<button data-tab="locations" class="${X.tab==='locations'?'active':''}">Marbetes</button><button data-tab="admin" class="${X.tab==='admin'?'active':''}">Admin</button>`:''}</nav>`}
function shell(){let body=X.tab==='scan'?X.scanView():X.tab==='inventory'?X.inventoryView():X.tab==='locations'?X.locationsView():X.adminView();app.innerHTML=`<div class="wrap"><div class="top"><div><h2 style="margin:0">Control de Bodega</h2><div class="small">${X.esc(X.S.nombre)}${X.S.puesto?' · '+X.esc(X.S.puesto):''}</div></div><button id="logout" class="btn-light">Salir</button></div>${body}</div>${nav()}`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{X.tab=b.dataset.tab;X.stopScanner();X.render()});$('logout').onclick=async()=>{X.stopScanner();localStorage.removeItem('bodegaEmpleado');await X.sb.auth.signOut();X.S=null;X.prod=null;X.locs=[];X.render()};X.wire()}
X.cam=async(cb,label)=>{try{await X.startScanner(cb,label)}catch{const z=$('msg')||$('marMsg')||$('asMsg');if(z)z.innerHTML='<div class="error">No se pudo abrir la cámara. Revisa el permiso del navegador.</div>'}};
