import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const URL='https://dkqovohxkxlcccvagpij.supabase.co';
const KEY='sb_publishable_iz06RtaObND0dWOpuX2vKg_wZVbrZCv';
const sbReset=createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const sbEmployeeTest=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const escReset=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));

function newPin(used){const a=new Uint32Array(1);let pin='';do{crypto.getRandomValues(a);pin=String(10000000+(a[0]%90000000))}while(used.has(pin));used.add(pin);return pin}
function csvDownload(rows){const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=['Nombre,Clave,PIN,Puesto,Prueba',...rows.map(r=>[r.nombre,r.clave,r.pin,r.puesto,'OK'].map(q).join(','))].join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`accesos_empleados_verificados_${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function employeeData(){const[er,ar]=await Promise.all([sbReset.from('empleados_operativos').select('id,clave,nombre,puesto,activo').eq('activo',true).order('nombre'),sbReset.from('empleado_operativo_departamentos').select('empleado_id,departamento_id')]);if(er.error)throw er.error;if(ar.error)throw ar.error;return{employees:er.data||[],assignments:ar.data||[]}}
async function resetOne(emp,assignments,pin){const deps=assignments.filter(x=>x.empleado_id===emp.id).map(x=>x.departamento_id);const r=await sbReset.rpc('admin_guardar_empleado',{p_id:emp.id,p_clave:String(emp.clave||'10'),p_nombre:emp.nombre,p_puesto:emp.puesto||'',p_pin:pin,p_activo:true,p_departamentos:deps});if(r.error)throw r.error}
async function verifyEmployee(emp,pin){
  // El login real valida Clave + PIN como anónimo y SOLO después abre la sesión operativa.
  await sbEmployeeTest.auth.signOut().catch(()=>{});
  const v=await sbEmployeeTest.rpc('validar_empleado',{p_clave:String(emp.clave||'10'),p_pin:pin});
  if(v.error)throw v.error;
  const row=v.data?.[0];
  if(!row||String(row.empleado_id)!==String(emp.id)||String(row.clave)!==String(emp.clave||'10'))return false;
  const s=await sbEmployeeTest.auth.signInWithPassword({email:'10@bodega.local',password:'bodega-10-1010'});
  if(s.error)throw new Error('La sesión operativa 10 no pudo abrirse. No se entregaron PINs sin probar.');
  await sbEmployeeTest.auth.signOut().catch(()=>{});
  return true;
}
async function resetAndVerify(emp,assignments,used){for(let n=0;n<3;n++){const pin=newPin(used);await resetOne(emp,assignments,pin);if(await verifyEmployee(emp,pin))return pin}throw new Error(`No fue posible validar el acceso de ${emp.nombre}. Se detuvo el proceso para no entregar una clave defectuosa.`)}

async function resetAll(button,panel){if(!confirm('Se reemplazarán los PIN actuales de todos los empleados activos y la app probará cada acceso completo antes de mostrarlo. ¿Continuar?'))return;button.disabled=true;button.textContent='Preparando prueba…';const status=panel.querySelector('[data-reset-status]');status.innerHTML='<p class="muted">Preparando verificación de accesos…</p>';try{const{employees,assignments}=await employeeData();if(!employees.length)throw new Error('No hay empleados activos para restablecer.');const used=new Set(),rows=[];for(let i=0;i<employees.length;i++){const emp=employees[i];button.textContent=`Reparando y probando ${i+1}/${employees.length}…`;status.innerHTML=`<p class="muted">Probando acceso ${i+1} de ${employees.length}: ${escReset(emp.nombre)}</p>`;const pin=await resetAndVerify(emp,assignments,used);rows.push({nombre:emp.nombre,clave:String(emp.clave||'10'),pin,puesto:emp.puesto||''})}window.__employeeResetRows=rows;status.innerHTML=`<div class="success">✓ ${rows.length}/${rows.length} accesos reparados y probados correctamente: PIN validado + sesión operativa abierta.</div><p class="tiny muted">Solo aparecen PINs que pasaron el flujo real de inicio de sesión. Los PIN anteriores ya no sirven.</p><div class="table-scroll"><table><thead><tr><th>Empleado</th><th>Clave</th><th>PIN nuevo</th><th>Prueba</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${escReset(r.nombre)}</td><td>${escReset(r.clave)}</td><td><b>${escReset(r.pin)}</b></td><td><b>✓ OK</b></td></tr>`).join('')}</tbody></table></div><button type="button" class="secondary" id="downloadEmployeePins">Descargar accesos verificados CSV</button>`;document.getElementById('downloadEmployeePins').onclick=()=>csvDownload(rows)}catch(e){status.innerHTML=`<div class="error"><b>La reparación se detuvo.</b><br>${escReset(e?.message||'No se pudieron verificar los accesos.')}</div><p class="tiny muted">No entregues como válidos los PIN que no tengan ✓ OK.</p>`}finally{await sbEmployeeTest.auth.signOut().catch(()=>{});button.disabled=false;button.textContent='Reparar y probar todos los accesos'}}

async function resetSingle(id,button){try{const{employees,assignments}=await employeeData(),emp=employees.find(x=>x.id===id);if(!emp)throw new Error('Empleado no encontrado o inactivo.');button.disabled=true;button.textContent='Probando…';const pin=await resetAndVerify(emp,assignments,new Set());alert(`${emp.nombre}\nClave: ${emp.clave||'10'}\nPIN nuevo: ${pin}\nPrueba de acceso: ✓ OK\n\nSe validó el PIN y después se abrió correctamente la sesión operativa.`)}catch(e){alert(e?.message||'No se pudo reparar y probar el acceso.')}finally{await sbEmployeeTest.auth.signOut().catch(()=>{});button.disabled=false;button.textContent='Nuevo PIN probado'}}

function inject(){const empClave=document.getElementById('empClave'),body=document.getElementById('adminBody');if(!empClave||!body||body.dataset.employeeResetReady==='3')return;body.dataset.employeeResetReady='3';const panel=document.createElement('div');panel.className='notice';panel.innerHTML=`<h3>Accesos de empleados</h3><p>Esta herramienta cambia el PIN y comprueba exactamente el orden del login: primero Clave + PIN, después sesión operativa.</p><button type="button" class="danger" id="resetAllEmployeePins">Reparar y probar todos los accesos</button><div data-reset-status></div>`;body.prepend(panel);document.getElementById('resetAllEmployeePins').onclick=e=>resetAll(e.currentTarget,panel);document.querySelectorAll('[data-emp-toggle]').forEach(toggle=>{const row=toggle.closest('.product-row');if(!row||row.querySelector('[data-emp-reset]'))return;const b=document.createElement('button');b.type='button';b.className='mini';b.dataset.empReset=toggle.dataset.empToggle;b.textContent='Nuevo PIN probado';b.onclick=()=>resetSingle(toggle.dataset.empToggle,b);toggle.parentElement?.appendChild(b)})}
new MutationObserver(inject).observe(document.documentElement,{subtree:true,childList:true});inject();
