const X=B,$=X.$,esc=X.esc;
X.scanView=()=>`<section><div class="grid3">${['VENTA','DEVOLUCION','ENTRADA'].map(t=>`<button class="type ${X.tipo===t?'active':''}" data-type="${t}">${t==='VENTA'?'−':'+'}<br>${t==='DEVOLUCION'?'Devolución':t[0]+t.slice(1).toLowerCase()}</button>`).join('')}</div><button id="openCam" class="btn-accent" style="width:100%;margin:12px 0">📷 Escanear UPC, SKU o marbete</button><div class="card"><form id="lookup"><label>UPC / SKU / marbete</label><div class="row"><input id="code" placeholder="Escanea o escribe"><button class="btn-light" style="flex:0 0 auto">Buscar</button></div></form><div id="productBox" style="margin-top:12px">${X.prod?productCard():'<p class="sub">Escanea un UPC, SKU o marbete.</p>'}</div></div><div id="msg" style="margin-top:12px"></div></section>`;
function locHTML(){if(!X.locs.length)return'<div class="loc-empty">Ubicación todavía no asignada</div>';return`<div class="locations">${X.locs.map(x=>`<div class="loc"><b>${esc(x.marbetes?.zona||'')}</b> · ${esc(x.marbete_codigo)}${x.marbetes?.descripcion?`<div class="small">${esc(x.marbetes.descripcion)}</div>`:''}${x.cantidad!=null?`<div class="small">Cantidad: ${esc(x.cantidad)}</div>`:''}</div>`).join('')}</div>`}
function productCard(){const p=X.prod,st=p.stock<=0?'<span class="badge bad">Agotado</span>':p.stock<=p.stock_minimo?'<span class="badge warn">Stock bajo</span>':'<span class="badge good">Disponible</span>';return`<div><div class="small">SKU <b>${esc(p.sku)}</b>${p.upc?` · UPC <b>${esc(p.upc)}</b>`:''}</div><h3>${esc(p.descripcion)}</h3><p class="sub">${esc([p.marca,p.talla,p.color].filter(Boolean).join(' · '))} · ${X.money(p.precio)}</p><div class="row"><div><div class="small">Stock total</div><div class="stock">${p.stock}</div></div><div style="text-align:right">${st}</div></div><label>Ubicación / marbete</label>${locHTML()}<label>Cantidad</label><input id="qty" type="number" min="1" value="1"><label>Área del movimiento</label><select id="area"><option value="piso">Piso de venta</option><option value="bodega">Bodega</option><option value="caja">Caja</option></select><label>Nota</label><input id="note" placeholder="Opcional"><button id="saveMove" class="btn" style="margin-top:14px">Registrar movimiento</button></div>`}
X.inventoryView=()=>`<section><div class="card"><label>Buscar inventario</label><input id="invSearch" placeholder="UPC, SKU, descripción, marca, talla o color"><div id="invList" style="margin-top:10px"><p class="sub">Cargando…</p></div></div></section>`;
X.findProduct=async code=>{code=String(code||'').trim();if(!code)return null;const r=await X.sb.rpc('buscar_producto_codigo',{p_codigo:code});if(!r.error&&r.data?.length)return r.data[0];const s=code.replace(/,/g,''),q=await X.sb.from('productos').select('*').eq('activo',true).or(`sku.eq.${s},upc.eq.${s}`).limit(1);return q.data?.[0]||null};
async function loadLoc(sku){const r=await X.sb.from('producto_marbetes').select('cantidad,marbete_codigo,marbetes(codigo,zona,descripcion,activo)').eq('sku',sku);X.locs=r.error?[]:(r.data||[]).filter(x=>x.marbetes?.activo!==false)}
async function lookup(code){code=String(code||'').trim();if(!code)return;const p=await X.findProduct(code);if(p){X.prod=p;await loadLoc(p.sku);X.render();setTimeout(()=>msg(code===p.sku?`SKU ${p.sku} encontrado.`:`UPC ${code} → SKU ${p.sku}`),0);return}const r=await X.sb.from('marbetes').select('codigo,zona,descripcion').eq('codigo',code).eq('activo',true).maybeSingle();X.prod=null;X.locs=[];X.render();setTimeout(()=>r.data?msg(`<b>Marbete ${esc(r.data.codigo)}</b><br><b>${esc(r.data.zona)}</b>${r.data.descripcion?' · '+esc(r.data.descripcion):''}`,'success',true):msg(`Código ${code} no encontrado.`,'error'),0)}
function msg(t,c='success',html=false){if($('msg'))$('msg').innerHTML=`<div class="${c}">${html?t:esc(t)}</div>`}
async function move(){const q=Math.max(1,Number($('qty').value)||1);if(X.tipo==='VENTA'&&q>X.prod.stock)return msg(`Stock insuficiente. Hay ${X.prod.stock}.`,'error');const b=$('saveMove');b.disabled=true;const r=await X.sb.rpc('registrar_movimiento_identificado',{p_id:X.uuid(),p_sku:X.prod.sku,p_tipo:X.tipo,p_cantidad:q,p_area:$('area').value,p_nota:$('note').value.trim()||null,p_empleado_nombre:X.S.mode==='employee'?X.S.nombre:null,p_empleado_puesto:X.S.mode==='employee'?X.S.puesto:null});b.disabled=false;if(r.error)return msg(r.error.message,'error');const row=Array.isArray(r.data)?r.data[0]:r.data;X.prod={...X.prod,stock:row?.stock_resultante??X.prod.stock};await loadLoc(X.prod.sku);X.render();setTimeout(()=>msg(`Movimiento registrado. Stock actual: ${X.prod.stock}`),0)}
function invWire(){let t;$('invSearch').oninput=()=>{clearTimeout(t);t=setTimeout(()=>inventory($('invSearch').value),180)};inventory('')}
async function inventory(q){let req=X.sb.from('productos').select('sku,upc,descripcion,marca,talla,color,precio,stock,stock_minimo').eq('activo',true).order('descripcion').limit(100);q=String(q||'').trim();if(q){const s=q.replace(/[,%]/g,' ');req=req.or(`sku.ilike.%${s}%,upc.ilike.%${s}%,descripcion.ilike.%${s}%,marca.ilike.%${s}%,talla.ilike.%${s}%,color.ilike.%${s}%`)}const r=await req;$('invList').innerHTML=r.error?'<div class="error">No se pudo cargar.</div>':(r.data||[]).map(p=>`<div class="product"><div><b>${esc(p.descripcion)}</b><div class="small">SKU ${esc(p.sku)}${p.upc?' · UPC '+esc(p.upc):''} · ${esc([p.marca,p.talla,p.color].filter(Boolean).join(' · '))}</div></div><div style="text-align:right"><div class="stock">${p.stock}</div><div class="small">${X.money(p.precio)}</div></div></div>`).join('')||'<p class="sub">Sin resultados.</p>'}
X.wire=()=>{document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{X.tipo=b.dataset.type;X.render()});if(X.tab==='scan'){$('openCam').onclick=()=>X.cam(v=>lookup(v),'UPC, SKU o marbete');$('lookup').onsubmit=e=>{e.preventDefault();lookup($('code').value)};$('saveMove')?.addEventListener('click',move)}if(X.tab==='inventory')invWire();if(X.tab==='locations')X.locationsWire();if(X.tab==='admin')X.adminLoad()};
