const X=B,$=X.$,esc=X.esc;
X.scanView=()=>`<section><div class="grid2"><button class="type ${X.tipo==='ENTRADA'?'active':''}" data-type="ENTRADA">＋<br>Entrada a bodega</button><button class="type ${X.tipo==='SALIDA'?'active':''}" data-type="SALIDA">−<br>Salida de bodega</button></div>${X.lastMsg?`<div class="success">${esc(X.lastMsg)}</div>`:''}<button id="openCam" class="btn-accent" style="width:100%;margin:12px 0">📷 Escanear siguiente UPC o SKU</button><div class="card"><form id="lookup"><label>UPC / SKU</label><div class="row"><input id="code" inputmode="numeric" autocomplete="off" placeholder="Escanea o escribe"><button class="btn-light" style="flex:0 0 auto">Buscar</button></div></form><div id="productBox" style="margin-top:12px">${X.prod?productCard():'<p class="sub">Listo para registrar el siguiente movimiento. Al guardar se limpia automáticamente y vuelve a abrir el lector.</p>'}</div></div><div id="msg" style="margin-top:12px"></div></section>`;
function locHTML(){if(!X.locs.length)return'<div class="loc-empty">Sin ubicación asignada todavía</div>';return`<div class="locations">${X.locs.map(x=>`<div class="loc"><b>${esc(x.marbetes?.zona||'')}</b> · ${esc(x.marbete_codigo)}${x.marbetes?.descripcion?`<div class="small">${esc(x.marbetes.descripcion)}</div>`:''}${x.cantidad!=null?`<div class="small">Cantidad ubicada: ${esc(x.cantidad)}</div>`:''}</div>`).join('')}</div>`}
function marbeteSelect(){const b=X.locs.filter(x=>x.marbetes?.zona==='BODEGA');if(!b.length)return`<select id="marbete"><option value="">Sin marbete específico</option></select>`;return`<select id="marbete"><option value="">Sin marbete específico</option>${b.map((x,i)=>`<option value="${esc(x.marbete_codigo)}" ${b.length===1&&i===0?'selected':''}>${esc(x.marbete_codigo)}${x.marbetes?.descripcion?' · '+esc(x.marbetes.descripcion):''}${x.cantidad!=null?' · '+esc(x.cantidad)+' pzas':''}</option>`).join('')}</select>`}
function productCard(){const p=X.prod,st=p.stock<=0?'<span class="badge bad">Sin stock</span>':p.stock<=p.stock_minimo?'<span class="badge warn">Stock bajo</span>':'<span class="badge good">Disponible</span>';return`<div><div class="small">SKU <b>${esc(p.sku)}</b>${p.upc?` · UPC <b>${esc(p.upc)}</b>`:''}</div><h3>${esc(p.descripcion)}</h3><p class="sub">${esc([p.marca,p.talla,p.color].filter(Boolean).join(' · '))}${p.precio!=null?' · '+X.money(p.precio):''}</p><div class="row"><div><div class="small">Stock total</div><div class="stock">${p.stock}</div></div><div style="text-align:right">${st}</div></div><label>Ubicaciones conocidas</label>${locHTML()}<label>${X.tipo==='ENTRADA'?'Guardar en marbete de bodega':'Sacar de marbete de bodega'} (opcional)</label>${marbeteSelect()}<label>Cantidad</label><input id="qty" type="number" min="1" value="1" inputmode="numeric"><label>Nota (opcional)</label><input id="note" autocomplete="off" placeholder="Ej. llegó proveedor / sube a piso"><button id="saveMove" class="btn ${X.tipo==='SALIDA'?'danger-solid':''}" style="margin-top:14px">${X.tipo==='ENTRADA'?'Registrar entrada':'Registrar salida'}</button></div>`}
X.inventoryView=()=>`<section><div class="card"><label>Buscar inventario</label><input id="invSearch" autocomplete="off" placeholder="UPC, SKU, descripción, marca, talla o color"><div id="invList" style="margin-top:10px"><p class="sub">Cargando…</p></div></div></section>`;
X.findProduct=async code=>{code=String(code||'').trim();if(!code)return null;const r=await X.sb.rpc('buscar_producto_codigo',{p_codigo:code});if(!r.error&&r.data?.length)return r.data[0];const s=code.replace(/[^0-9A-Za-z_-]/g,''),q=await X.sb.from('productos').select('*').eq('activo',true).or(`sku.eq.${s},upc.eq.${s}`).limit(1);return q.data?.[0]||null};
async function loadLoc(sku){const r=await X.sb.from('producto_marbetes').select('cantidad,marbete_codigo,marbetes(codigo,zona,descripcion,activo)').eq('sku',sku);X.locs=r.error?[]:(r.data||[]).filter(x=>x.marbetes?.activo!==false)}
async function lookup(code){code=String(code||'').trim();if(!code)return;X.lastMsg='';const p=await X.findProduct(code);if(p){X.prod=p;await loadLoc(p.sku);X.render();setTimeout(()=>msg(code===p.sku?`SKU ${p.sku} encontrado.`:`UPC ${code} → SKU ${p.sku}`),0);return}const r=await X.sb.from('marbetes').select('codigo,zona,descripcion').eq('codigo',code).eq('activo',true).maybeSingle();X.prod=null;X.locs=[];X.render();setTimeout(()=>r.data?msg(`<b>Marbete ${esc(r.data.codigo)}</b><br><b>${esc(r.data.zona)}</b>${r.data.descripcion?' · '+esc(r.data.descripcion):''}`,'success',true):msg(`Código ${code} no encontrado.`,'error'),0)}
function msg(t,c='success',html=false){if($('msg'))$('msg').innerHTML=`<div class="${c}">${html?t:esc(t)}</div>`}
async function move(){if(X.busy||!X.prod)return;const q=Math.max(1,Number($('qty').value)||1);if(X.tipo==='SALIDA'&&q>X.prod.stock)return msg(`Stock insuficiente. Hay ${X.prod.stock}.`,'error');const b=$('saveMove');X.busy=true;b.disabled=true;b.textContent='Registrando…';const sku=X.prod.sku,desc=X.prod.descripcion,tipo=X.tipo,mar=$('marbete')?.value||'',nota=$('note').value.trim()||null;const r=await X.sb.rpc('registrar_movimiento_bodega',{p_id:X.uuid(),p_sku:sku,p_tipo:tipo,p_cantidad:q,p_nota:nota,p_empleado_nombre:X.S.mode==='employee'?X.S.nombre:null,p_empleado_puesto:X.S.mode==='employee'?X.S.puesto:null,p_marbete_codigo:mar||null});X.busy=false;if(r.error){b.disabled=false;b.textContent=tipo==='ENTRADA'?'Registrar entrada':'Registrar salida';return msg(r.error.message,'error')}const row=Array.isArray(r.data)?r.data[0]:r.data;X.prod=null;X.locs=[];X.lastMsg=`${tipo==='ENTRADA'?'Entrada':'Salida'} registrada: ${q} pza${q===1?'':'s'} · SKU ${sku} · stock ${row?.stock_resultante??'actualizado'} · ${desc}`;X.render();setTimeout(()=>X.cam(v=>lookup(v),'UPC o SKU'),250)}
function invWire(){let t;const i=$('invSearch');i.oninput=()=>{clearTimeout(t);t=setTimeout(()=>inventory(i.value),180)};inventory('')}
async function inventory(q){q=String(q||'').trim();let req=X.sb.from('productos').select('sku,upc,descripcion,marca,talla,color,precio,stock,stock_minimo,updated_at').eq('activo',true);if(q){const s=q.replace(/[,%]/g,' ').trim();req=req.or(`sku.ilike.%${s}%,upc.ilike.%${s}%,descripcion.ilike.%${s}%,marca.ilike.%${s}%,talla.ilike.%${s}%,color.ilike.%${s}%`).limit(80)}else req=req.order('updated_at',{ascending:false}).limit(50);const r=await req;if(!$('invList'))return;$('invList').innerHTML=r.error?'<div class="error">No se pudo cargar.</div>':(r.data||[]).map(p=>`<div class="product"><div><b>${esc(p.descripcion)}</b><div class="small">SKU ${esc(p.sku)}${p.upc?' · UPC '+esc(p.upc):''} · ${esc([p.marca,p.talla,p.color].filter(Boolean).join(' · '))}</div></div><div style="text-align:right"><div class="stock">${p.stock}</div><div class="small">${X.money(p.precio)}</div></div></div>`).join('')||'<p class="sub">Sin resultados.</p>'}
X.wire=()=>{document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{X.tipo=b.dataset.type;X.render()});if(X.tab==='scan'){$('openCam').onclick=()=>X.cam(v=>lookup(v),'UPC o SKU');$('lookup').onsubmit=e=>{e.preventDefault();lookup($('code').value)};$('saveMove')?.addEventListener('click',move);if(!X.prod)setTimeout(()=>$('code')?.focus(),50)}if(X.tab==='inventory')invWire();if(X.tab==='history')X.historyLoad();if(X.tab==='locations')X.locationsWire();if(X.tab==='admin')X.adminLoad()};
